version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "p45sw0rd"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "strider"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge