// Code generated by MockGen. DO NOT EDIT.
// Source: api/routes/user/service.go

// Package mock_user is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mysql "strider-backend-test.com/adapter/mysql"
	model "strider-backend-test.com/api/routes/user/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// UpdateCount mocks base method.
func (m *MockService) UpdateCount(ctx context.Context, tx mysql.Transaction, request *model.UpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCount", ctx, tx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCount indicates an expected call of UpdateCount.
func (mr *MockServiceMockRecorder) UpdateCount(ctx, tx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCount", reflect.TypeOf((*MockService)(nil).UpdateCount), ctx, tx, request)
}
